FORMAT: 1A
HOST: https://gw.hii.in.th/thing

# Group Introduction

# Thing API

  เอกสารการสเปค **Thing API.**


# Group Authorization

## การสร้าง Device access token [POST /auth/user/tokens]
  การใช้งาน api จำเป็นต้องมี device access token

+ Request (application/json)

    + Attributes (LoginBody , fixed-type)

+ Response 201 (application/json)

    + Attributes (AccessTokenBody , fixed-type)

# Group การวัดค่า

## เปิด Session [POST /sessions]

  ก่อนเริ่มการใส่ข้อมูลของผู้วัดแต่ละคน ต้องมีการลงทะเบียนการวัดก่อน

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (CreateSession , fixed-type)

+ Response 201 (application/json)

    + Attributes (SessionReturn , fixed-type)

## ใส่ข้อมูลส่วนสูง [POST /session/{sessionId}/heights]

    ใส่ข้อมูลส่วนสูง

+ Parameters
    + sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string,required)
      ``หมายเลข session id``

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (Height , fixed-type)

+ Response 201 (application/json)

    + Attributes (HeightReturn , fixed-type)

## ข้อมูลน้ำหนัก [POST /session/{sessionId}/weights]

    ใส่ข้อมูลน้ำหนัก

+ Parameters
    + sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string,required)
      ``หมายเลข session id``

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (Weight , fixed-type)

+ Response 201 (application/json)

    + Attributes (WightReturn , fixed-type)

## ข้อมูลค่าออกซิเจนในเลือด [POST /session/{sessionId}/spo2]

    ใส่ข้อมูลออกซิเจนในเลือด

+ Parameters
    + sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string,required)
      ``หมายเลข session id``

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (SPO2 , fixed-type)

+ Response 201 (application/json)

    + Attributes (SPO2Return , fixed-type)

## ข้อมูลอุณหภูมิ [POST /session/{sessionId}/temperature]

    ใส่ข้อมูลอุณหภูมิ

+ Parameters
    + sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string,required)
      ``หมายเลข session id``

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (Temperature , fixed-type)

+ Response 201 (application/json)

    + Attributes (TemperatureReturn , fixed-type)

## ข้อมูลความดันเลือด [POST /session/{sessionId}/blood-pressures]

    ใส่ข้อมูลอุณหภูมิ

+ Parameters
    + sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string,required)
      ``หมายเลข session id``

+ Request (application/json)

    + Headers

            Authorization: Bearer {access token}

    + Attributes (BloodPressure , fixed-type)

+ Response 201 (application/json)

    + Attributes (BloodPressureReturn , fixed-type)

## บันทึกผลพร้อมคืนค่าข้อมูลการวัด [POST /session/{sessionId}/commit]


## Data Structures

# BloodPressure (object)
+ sys: 130.0 (number, fixed-type)
+ dia: 98.0 (number, fixed-type)
+ pulse: 66.0 (number, fixed-type)

# BloodPressureReturn (BloodPressure)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, fixed-type)
+ level (BloodPressureLevel)
+ time: `2019-06-05T06:19:32+00:00` (string, fixed-type)

# BloodPressureLevel (enum)
+ isLow - ความดันต่ำ
+ isNormal - ความดันปกติ
+ isPreHigh - เสี่ยงความดันสูง
+ isHigh - ความดันสูง

# Temperature (object)
+ temperature: 37.1 (number, fixed-type)
+ type (TemperatureType)

# TemperatureReturn (Temperature)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, fixed-type)
+ time: `2019-06-05T06:19:30+00:00` (string, fixed-type)

# TemperatureType (enum)
+ INFRARED_CAMERA - กล้อง Infrared
+ INFRARED - Infrared sensor
+ PLATE - Sensor แบบแผ่น
+ UNDEFINED - ไม่ระบุ

# SPO2 (object)
+ spo2: 98.0 (number, fixed-type)
+ pulse: 66.0 (number, fixed-type)

# SPO2Return (SPO2)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, fixed-type)
+ time: `2019-06-05T06:19:29+00:00` (string, fixed-type)

# Weight (object)
+ weight: 48 (number, fixed-type)
+ type (WeightType)

# WightReturn (Weight)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, fixed-type)
+ time: `2019-06-05T06:19:27+00:00` (string, fixed-type)

# WeightType (enum)
+ WHEELCHAIR - รถวีลแชร์
+ CHAIR - แบบนั้งเก้าอี้
+ UNDEFINED - ไม่ระบุ เช่น กรอกเอง, อื่นๆ

# Height (object)
+ height: 168 (number, fixed-type) - ข้อมูลส่วนสูง

# HeightReturn (Height)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, fixed-type)
+ time: `2019-06-05T06:19:25+00:00` (string, fixed-type)

# LoginBody (object)
+ username: `user999` (string, required)
+ password: `pa$$word` (string, required)

# AccessTokenBody (object)
+ accessToken: `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9` (string,required) - รหัส access token

# CreateSession (object)
+ citizenId: `1222311234321` (string, required) - เลขบัตรประชาชน
+ citizenIdInput (CitizenInput, required) - ลักษณะการนำเข้าข้อมูล
+ birthDate: `1990-06-05` (string, required) - วันเกิด
+ name: `ธนชัย ทองคำ` - ชื่อ นามสกุล
+ sex (Sex) - เพศ
+ whoDid (WhoDid) - ใครเป็นคนวัดให้

# SessionReturn (object)
+ sessionId: `bba8104c-8754-11e9-bc42-526af7764f64` (string, required) - หมายเลข session
+ subject (Person)

# Person (object)
+ type: `Person` (string, fixed) - ค่าคงที่
+ age: 43 (number) - อายุ
+ height: 170.0 (number) - ส่วนสูง
+ weigth: 65.2 (number) - น้ำหนัก
+ bloodPressure (BloodPressure) - ข้อมูลความดัน

# BloodPressure (object)
+ sys: 110 (number)
+ dia: 60 (number)
+ level (BloodPressureLevel)

# BloodPressureLevel (enum)
+ LOW
+ NORMAL
+ HEIGHT

# Sex (enum)
+ MALE - ผู้ชาย
+ FEMAIL - ผู้หญิง

# CitizenInput (enum)
+ CARD - บัตรประชาชน
+ FACE - ใบหน้า
+ TYPING - ด้วยการพิมพ์

# WhoDid (enum)
+ SELF - วัดด้วยตัวเอง
+ OFFICER - วัดด้วยเจ้าหน้าที่
