FORMAT: 1A
HOST: https://gw.hii.in.th/thing

# Group Introduction

# Thing API

  เอกสารการสเปค **Thing API.**


# Group Authorization

  การใช้งาน จำเป็นต้องมี access token

    `Authorization: Bearer {token}`

# Group การวัดค่า

## เปิด Session [POST /room]

  ก่อนเริ่มการใส่ข้อมูลผู้วัดแต่ละคน ต้องเริ่ม Session ก่อน

## Data Structures

# LoginBody (object)
+ username: `user999` (string, required)
+ password: `pa$$word` (string, required)
